version: "3.9"

services:
  mysql:
    image: mysql:8.0.41
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql-8.0.41
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - booking-network

  booking-service:
    build: .
    container_name: booking-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mysql-8.0.41?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SERVER_PORT: 8080
      JWT_SECRET_KEY: M0N2OArmuTzgyhbzdBmQeAqKKU/jacPLlDenKym6rYUM/abfXnH3WPpVHNPdEFkl
      JWT_VALID_DURATION: 3600
      JWT_REFRESH_DURATION: 7200
    depends_on:
      - mysql
    networks:
      - booking-network

volumes:
  mysql_data:

networks:
  booking-network: